name: CI

on: [push, pull_request]

  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    #  - name: Install fmt
    #    uses: maximeverreault/setup-fmt@v1.0.0
    #    id: install_fmt
    #    with:
    #      version: 9.1.0
    #      directory: /usr/local
    #    env:
    #      GH_TOKEN: ${{ github.token }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson ninja

      - name: Configure
        run: meson setup build

      - name: Build
        run: meson compile -C build

      - name: Run tests
        run: meson test -C build
