name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson ninja
          sudo apt-get install libfmt-dev

      - name: Configure
        run: meson setup --reconfigure build

      - name: Build
        run: meson compile -C build

      - name: Configure
        run: meson setup --reconfigure build

      - name: Run tests
        run: make tests

      - name: Run examples
        run: |
          meson install -C build
          make examples
